name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:  [ "v**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Timestamp
      id: timestamp
      run: echo ::set-output name=TIMESTAMP::$(date +%s)

    - name: Build the Docker image 'master'
      run: docker build . --file Dockerfile --tag technbolts/jwtd:${{ steps.timestamp.outputs.TIMESTAMP }}
      if: ${{ github.ref == 'refs/heads/master' }}
    - name: Build the Docker image 'master' as latest
      run: docker tag technbolts/jwtd:${{ steps.timestamp.outputs.TIMESTAMP }} technbolts/jwtd:latest
      if: ${{ github.ref == 'refs/heads/master' }}
      
    - name: Build the Docker image 'tag'
      run: docker build . --file Dockerfile --tag technbolts/jwtd:${{ steps.get_version.outputs.VERSION }}
      if: ${{ github.ref != 'refs/heads/master' }}
    - name: Build the Docker image 'tag' as latest
      run: docker tag technbolts/jwtd:${{ steps.get_version.outputs.VERSION }} technbolts/jwtd:latest
      if: ${{ github.ref != 'refs/heads/master' }}

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      if: ${{ github.ref != 'refs/heads/master' }}

    - name: Push the Docker image 'tag'
      run: docker push technbolts/jwtd:${{ steps.get_version.outputs.VERSION }}
      if: ${{ github.ref != 'refs/heads/master' }}

    - name: Push the Docker image 'tag' as latest
      run: docker push technbolts/jwtd:latest
      if: ${{ github.ref != 'refs/heads/master' }}

